#!/usr/bin/env bash
# setup-frpc.sh — Install frpc on a Mac Mini and connect it to the VPS relay.
# Idempotent: safe to re-run.
#
# Usage:
#   ./setup-frpc.sh <subdomain> <token> [options]
#
# Arguments:
#   subdomain   Tenant subdomain (e.g. "alice")
#   token       Tunnel auth token (from octos admin create-tenant)
#
# Options:
#   --server <addr>       frps server address (default: 163.192.33.32)
#   --port <port>         frps control port (default: 7000)
#   --local-port <port>   Local octos serve port (default: 8080)
#   --ssh-port <port>     SSH tunnel remote port (default: 6001)
#   --domain <domain>     Base domain (default: octos-cloud.org)
#   --frpc-version <ver>  frpc version (default: 0.61.1)

set -euo pipefail

# ── Parse arguments ───────────────────────────────────────────────────
if [ $# -lt 2 ]; then
    echo "Usage: $0 <subdomain> <token> [options]"
    echo ""
    echo "Options:"
    echo "  --server <addr>       frps server (default: 163.192.33.32)"
    echo "  --port <port>         frps port (default: 7000)"
    echo "  --local-port <port>   Local octos port (default: 8080)"
    echo "  --ssh-port <port>     SSH tunnel port (default: 6001)"
    echo "  --domain <domain>     Base domain (default: octos-cloud.org)"
    exit 1
fi

SUBDOMAIN="$1"
TUNNEL_TOKEN="$2"
shift 2

# Defaults
FRPS_SERVER="163.192.33.32"
FRPS_PORT=7000
LOCAL_PORT=8080
SSH_PORT=6001
TUNNEL_DOMAIN="octos-cloud.org"
FRPC_VERSION="0.61.1"

# Parse optional flags
while [ $# -gt 0 ]; do
    case "$1" in
        --server)     FRPS_SERVER="$2"; shift 2 ;;
        --port)       FRPS_PORT="$2"; shift 2 ;;
        --local-port) LOCAL_PORT="$2"; shift 2 ;;
        --ssh-port)   SSH_PORT="$2"; shift 2 ;;
        --domain)     TUNNEL_DOMAIN="$2"; shift 2 ;;
        --frpc-version) FRPC_VERSION="$2"; shift 2 ;;
        *)            echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "==> Setting up frpc tunnel for ${SUBDOMAIN}.${TUNNEL_DOMAIN}"

# ── Detect architecture ──────────────────────────────────────────────
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)       FRP_ARCH="amd64" ;;
    aarch64|arm64) FRP_ARCH="arm64" ;;
    *)            echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac

OS=$(uname -s | tr '[:upper:]' '[:lower:]')

# ── Install frpc binary ──────────────────────────────────────────────
if [ -f /usr/local/bin/frpc ]; then
    CURRENT=$(/usr/local/bin/frpc --version 2>/dev/null || echo "unknown")
    echo "    frpc already installed (version: ${CURRENT})"
else
    echo "    Downloading frpc v${FRPC_VERSION}..."
    FRP_TMPDIR=$(mktemp -d /tmp/frpc-install.XXXXXX)
    trap 'rm -rf "$FRP_TMPDIR"' EXIT

    TARBALL="frp_${FRPC_VERSION}_${OS}_${FRP_ARCH}.tar.gz"
    URL="https://github.com/fatedier/frp/releases/download/v${FRPC_VERSION}/${TARBALL}"
    curl -fsSL -o "${FRP_TMPDIR}/${TARBALL}" "$URL"
    tar -xzf "${FRP_TMPDIR}/${TARBALL}" -C "$FRP_TMPDIR"
    echo "    (sudo is needed to install frpc to /usr/local/bin)"
    sudo mkdir -p /usr/local/bin
    sudo cp "${FRP_TMPDIR}/frp_${FRPC_VERSION}_${OS}_${FRP_ARCH}/frpc" /usr/local/bin/frpc
    sudo chmod 0755 /usr/local/bin/frpc
    echo "    frpc installed to /usr/local/bin/frpc"
fi

# ── Write frpc config ────────────────────────────────────────────────
echo "    (sudo is needed to write config to /etc/frp)"
sudo mkdir -p /etc/frp
sudo tee /etc/frp/frpc.toml > /dev/null << EOF
# frpc config for ${SUBDOMAIN}.${TUNNEL_DOMAIN}
# Generated by setup-frpc.sh — safe to re-run

serverAddr = "${FRPS_SERVER}"
serverPort = ${FRPS_PORT}

auth.method = "token"
auth.token = "${TUNNEL_TOKEN}"

log.to = "/var/log/frpc.log"
log.level = "info"
log.maxDays = 7

[[proxies]]
name = "${SUBDOMAIN}-web"
type = "http"
localPort = ${LOCAL_PORT}
customDomains = ["${SUBDOMAIN}.${TUNNEL_DOMAIN}"]

[[proxies]]
name = "${SUBDOMAIN}-ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = ${SSH_PORT}
EOF

echo "    Config written to /etc/frp/frpc.toml"

# ── Create service ───────────────────────────────────────────────────
echo "    (sudo is needed to install the frpc system service)"
if [ "$OS" = "darwin" ]; then
    # macOS: LaunchDaemon (runs as root, survives logout)
    PLIST_PATH="/Library/LaunchDaemons/io.octos.frpc.plist"

    sudo tee "$PLIST_PATH" > /dev/null << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.octos.frpc</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/frpc</string>
        <string>-c</string>
        <string>/etc/frp/frpc.toml</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/var/log/frpc.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/frpc.log</string>
</dict>
</plist>
PLIST_EOF

    sudo chown root:wheel "$PLIST_PATH"
    sudo chmod 644 "$PLIST_PATH"

    # Also clean up legacy LaunchAgent if present
    launchctl unload "$HOME/Library/LaunchAgents/io.octos.frpc.plist" 2>/dev/null || true
    rm -f "$HOME/Library/LaunchAgents/io.octos.frpc.plist"

    sudo launchctl unload "$PLIST_PATH" 2>/dev/null || true
    sudo launchctl load "$PLIST_PATH"
    echo "    LaunchDaemon loaded (io.octos.frpc)"
else
    # Linux: systemd
    sudo tee /etc/systemd/system/frpc.service > /dev/null << SYSTEMD_EOF
[Unit]
Description=frpc tunnel client for octos
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frpc -c /etc/frp/frpc.toml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SYSTEMD_EOF

    sudo systemctl daemon-reload
    sudo systemctl enable frpc
    sudo systemctl restart frpc
    echo "    systemd service started (frpc)"
fi

# ── Test tunnel connectivity ──────────────────────────────────────────
echo ""
echo "==> Waiting for tunnel to establish..."
sleep 3

# Check frpc is running
if pgrep -x frpc > /dev/null 2>&1; then
    echo "    frpc is running (PID: $(pgrep -x frpc))"
else
    echo "    WARNING: frpc does not appear to be running"
    echo "    Check logs: cat /tmp/frpc.log"
fi

# Check local octos
if curl -sf --max-time 3 "http://localhost:${LOCAL_PORT}/api/status" > /dev/null 2>&1; then
    echo "    octos serve is running on port ${LOCAL_PORT}"
else
    echo "    NOTE: octos serve is not running on port ${LOCAL_PORT}"
    echo "    Start it with: octos serve --port ${LOCAL_PORT}"
fi

echo ""
echo "==> Setup complete!"
echo "    Dashboard:  https://${SUBDOMAIN}.${TUNNEL_DOMAIN}"
echo "    SSH access: ssh -p ${SSH_PORT} $(whoami)@${TUNNEL_DOMAIN}"
