//! Harness starter: report generator producing a markdown artifact.
//!
//! Declares `primary = "reports/*.md"` and a `generate_report` spawn-only
//! tool. The tool writes a deterministic markdown file under
//! `<workspace_root>/reports/` so the workspace contract can resolve it.
//!
//! See `docs/OCTOS_HARNESS_DEVELOPER_GUIDE.md`.

#![deny(unsafe_code)]

use std::path::{Path, PathBuf};

use eyre::{Result, WrapErr};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct GenerateReportInput {
    /// Report topic; also used to derive the filename.
    pub topic: String,
    /// Optional body content. When absent, a stub body is written.
    #[serde(default)]
    pub body: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerateReportOutput {
    pub artifact_path: PathBuf,
}

/// Render a markdown report to `<workspace_root>/reports/<slug>.md`.
///
/// The written body is at least 256 bytes so the policy's
/// `file_size_min:$primary:256` validator passes on every successful run.
/// Returns the workspace-relative artifact path.
pub fn generate_report(
    workspace_root: &Path,
    input: &GenerateReportInput,
) -> Result<GenerateReportOutput> {
    let reports_dir = workspace_root.join("reports");
    std::fs::create_dir_all(&reports_dir)
        .wrap_err_with(|| format!("create reports dir failed: {}", reports_dir.display()))?;

    let slug = slugify(&input.topic);
    let relative = Path::new("reports").join(format!("{slug}.md"));
    let full = workspace_root.join(&relative);

    let body = input.body.as_deref().unwrap_or(DEFAULT_BODY);
    let rendered = render_markdown(&input.topic, body);
    std::fs::write(&full, rendered.as_bytes())
        .wrap_err_with(|| format!("write report failed: {}", full.display()))?;

    Ok(GenerateReportOutput {
        artifact_path: relative,
    })
}

const DEFAULT_BODY: &str = "This report was generated by the harness-starter-report template.\n\n\
    Replace this body with your real content. The harness runtime will verify \
    that the produced file exists and is at least 256 bytes before marking \
    the task ready. See docs/OCTOS_HARNESS_DEVELOPER_GUIDE.md for the full \
    contract reference.";

fn render_markdown(topic: &str, body: &str) -> String {
    let mut out = String::new();
    out.push_str("# ");
    out.push_str(topic);
    out.push_str("\n\n");
    out.push_str("_Generated by harness-starter-report._\n\n");
    out.push_str(body);
    out.push('\n');
    // Pad to ensure the `file_size_min:$primary:256` validator always passes
    // even for very short bodies. The padding is informational and harmless.
    while out.len() < 256 {
        out.push_str("\n<!-- padding for validator -->");
    }
    out
}

pub fn slugify(label: &str) -> String {
    let mut out = String::with_capacity(label.len());
    let mut last_dash = false;
    for c in label.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "report".to_string()
    } else {
        trimmed
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn should_slugify_topic_for_filename() {
        assert_eq!(slugify("Q1 Sales"), "q1-sales");
        assert_eq!(slugify(""), "report");
    }

    #[test]
    fn should_emit_markdown_with_topic_heading() {
        let tmp = tempfile::tempdir().unwrap();
        let input = GenerateReportInput {
            topic: "smoke".into(),
            body: None,
        };
        let out = generate_report(tmp.path(), &input).unwrap();

        let body = std::fs::read_to_string(tmp.path().join(&out.artifact_path)).unwrap();
        assert!(body.starts_with("# smoke"));
        assert!(body.len() >= 256, "must satisfy file_size_min:256");
    }

    #[test]
    fn should_respect_caller_supplied_body() {
        let tmp = tempfile::tempdir().unwrap();
        let custom = "caller-controlled body line\n".repeat(20);
        let input = GenerateReportInput {
            topic: "custom".into(),
            body: Some(custom.clone()),
        };
        let out = generate_report(tmp.path(), &input).unwrap();
        let body = std::fs::read_to_string(tmp.path().join(&out.artifact_path)).unwrap();
        assert!(body.contains("caller-controlled body"));
    }
}
